Update cli.yml

diff --git a/.github/workflows/cli.yml b/.github/workflows/cli.yml
--- a/.github/workflows/cli.yml
+++ b/.github/workflows/cli.yml
@@ -74,11 +74,18 @@ jobs:
       - name: Test Codes 2
         if: true
         run: |
+          echo $(gh cache list --repo $repo -k clang-22-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null | grep 'createdAt')
+          exit
+          false
           repo="${{ github.repository_owner }}/${{ github.event.repository.name }}"
-          gh cache list --repo $repo -k clang-22-nux-v1 --json  'createdAt' 2>/dev/null | grep 'createdAt' | cut -d'"' -f4
-          clang_cache_epoc_timestamp=$(date --date=$(gh cache list --repo $repo -k clang-22-linux-v1 --json  'createdAt' 2>/dev/null | grep 'createdAt' | cut -d'"' -f4) +%s 2>/dev/null)
-          echo $clang_cache_epoc_timestamp
-          echo $(date +%s)
+          clang_cache_epoc_timestamp=$(date --date=$(gh cache list --repo $repo -k clang-22-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null | grep 'createdAt' | cut -d'"' -f4) +%s 2>/dev/null)
+          clang_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
+          [ -z "$clang_latest_relase" ] && { echo "Failed to extract clang latest release";exit 1;false; }
+          clang_latest_release_date=$(date --date="$(echo "${clang_latest_relase}" | grep -Eo '[[:digit:]]{8}')" +%s)
+          if [ $clang_latest_release_date -gt $clang_cache_epoc_timestamp ];then
+            echo ""
+            echo "removing clang-22-${{ runner.os }}-v1 from cache ..."
+          fi
           
 
           
