Update cli.yml

diff --git a/.github/workflows/cli.yml b/.github/workflows/cli.yml
--- a/.github/workflows/cli.yml
+++ b/.github/workflows/cli.yml
@@ -75,21 +75,31 @@ jobs:
         if: true
         run: |
           repo="${{ github.repository_owner }}/${{ github.event.repository.name }}"
-          clang_cache_creation_time=$(gh cache list --repo $repo -k clang-22-${{ runner.os }}-v2 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
-          if [ ! -z "${clang_cache_creation_time}" ];then
-            clang_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
-            [ -z "$clang_latest_relase" ] && { echo "Failed to extract clang latest release";exit 1;false; }
-            clang_latest_release_date=$(echo "${clang_latest_relase}" | grep -Eo '[[:digit:]]{8}' | sed -E 's/(.{4})(.{2})(.{2})/\1-\2-\3/g')
-            if [[ $clang_latest_release_date > $clang_cache_creation_time ]];then
-              echo "Latest release of clang-22: $(echo ${clang_latest_relase} | cut -d':' -f2-)"
-              echo "clang-22-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
-              echo "removing old clang-22-${{ runner.os }}-v1 from cache ..."
-              gh cache delete clang-22-${{ runner.os }}-v1 --repo $repo
-            fi
-            echo "Latest release of clang-22: $(echo ${clang_latest_relase} | cut -d':' -f2-)"
-            echo "clang-22-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
+          clang22_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
+          llvm_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/llvm/llvm-project/releases  | grep -Eo '"name":[^,]+' | grep 'Linux-X64.tar.xz"' | head -n 1)
+          [ -z "$clang22_latest_relase" ] && { echo "Failed to extract clang22 latest release";exit 1;false; }
+          [ -z "$llvm_latest_relase" ] && { echo "Failed to extract llvm latest release";exit 1;false; }
+          clang22_latest_release_date=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases |tr ',' '\n' | grep -E '("name":.*Clang.+.tar.gz"|"created_at":.+)' | sed -E -n '/"name":.+/{n;p}' | head -n 1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
+          llvm_latest_relase_date=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/llvm/llvm-project/releases |tr ',' '\n' | grep -E '("name":.+Linux-X64.tar.xz"|"created_at":.+)' | sed -E -n '/"name":.+/{n;p}' | head -n 1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
+          [ -z "$clang22_latest_release_date" ] && { echo "Failed to extract clang22 latest release date";exit 1;false; }
+          [ -z "$llvm_latest_relase_date" ] && { echo "Failed to extract llvm latest release date";exit 1;false; }
+          if [[ $clang22_latest_release_date > $llvm_latest_relase_date ]];then
+            clang22_compiler=true
+            latest_update_time=$clang22_latest_release_date
           else
-            echo "clang-22-${{ runner.os }}-v1 cache not found in ${repo}"
+            llvm_compiler=true
+            latest_update_time=$llvm_latest_relase_date
+          fi
+          echo "Latest release of $( [ "$clang22_compiler" == "true" ] && echo "clang-22" || echo "llvm"): ${latest_update_time}"
+          clang_cache_creation_time=$(gh cache list --repo $repo -k clang-${{ runner.os }}-v2 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+          if [ -n "${clang_cache_creation_time}" ];then
+            echo "clang-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
+            if [[ $latest_update_time > $clang_cache_creation_time ]];then
+              echo "removing old clang-${{ runner.os }}-v1 from cache ..."
+              gh cache delete clang-${{ runner.os }}-v1 --repo $repo
+            fi
+          else
+            echo "clang-${{ runner.os }}-v1 cache not found in ${repo}"
           fi
           
 
