Update fetch_patch.yml

diff --git a/.github/workflows/fetch_patch.yml b/.github/workflows/fetch_patch.yml
--- a/.github/workflows/fetch_patch.yml
+++ b/.github/workflows/fetch_patch.yml
@@ -63,6 +63,7 @@ jobs:
           #declare -a repo_commits=($(git log -n 200 --no-decorate | grep -E '^commit' | cut -d' ' -f2))
           if [ ${{ env.ksu_fork }} == 'KSUN' ];then
             git clone https://github.com/KernelSU-Next/KernelSU-Next KSU
+            use_pershoot_susfs=true
             
             #Add kernelnosu support to core_hook.c file
             kernelnosu=false
@@ -102,30 +103,37 @@ jobs:
               mv SukiSU-Ultra/kernel .
               rm -rf SukiSU-Ultra
             elif [ ${{ env.ksu_fork }} == 'KSUN'  ];then
-              SUSFS_BRANCH="gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}"
-              git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
-              susfs_version=$(grep '#define SUSFS_VERSION' ./susfs4ksu/kernel_patches/include/linux/susfs.h | awk -F'"' '{print $2}')
-              rm -rf susfs4ksu
-              echo "SusFS Version: $susfs_version"
-              case "$susfs_version" in
-                "v1.5.5"|"v1.5.6"|"v1.5.7")
-                  wget https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch
-                  cp "./0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch" "./ksun_susfs_latest.patch"
-                  ;;
-                "v1.5.8")
-                  wget https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch
-                  cp "./0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch" "./ksun_susfs_latest.patch"
-                  ;;
-                "v1.5.9")
-                  [ "${kernelnosu}" == "true" ] && patch_file="https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8-kernelnosu.patch" || patch_file="https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8.patch"
-                  wget ${patch_file}
-                  cp $(echo ${patch_file} | rev | cut -d '/' -f1 | rev) "./ksun_susfs_latest.patch"
-                  ;;
-                *)
-                  echo "Invalid version: $susfs_version"
-                  exit 1
-                  ;;
-              esac
+              if [ "${use_pershoot_susfs}" == "false" ];then
+                SUSFS_BRANCH="gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}"
+                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
+                susfs_version=$(grep '#define SUSFS_VERSION' ./susfs4ksu/kernel_patches/include/linux/susfs.h | awk -F'"' '{print $2}')
+                rm -rf susfs4ksu
+                echo "SusFS Version: $susfs_version"
+                case "$susfs_version" in
+                  "v1.5.5"|"v1.5.6"|"v1.5.7")
+                    wget https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch
+                    cp "./0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch" "./ksun_susfs_latest.patch"
+                    ;;
+                  "v1.5.8")
+                    wget https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch
+                    cp "./0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch" "./ksun_susfs_latest.patch"
+                    ;;
+                  "v1.5.9")
+                    [ "${kernelnosu}" == "true" ] && patch_file="https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8-kernelnosu.patch" || patch_file="https://raw.githubusercontent.com/ahmad24shargh/kernel_patches/refs/heads/main/next/0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8.patch"
+                    wget ${patch_file}
+                    cp $(echo ${patch_file} | rev | cut -d '/' -f1 | rev) "./ksun_susfs_latest.patch"
+                    ;;
+                  *)
+                    echo "Invalid version: $susfs_version"
+                    exit 1
+                    ;;
+                esac
+              else
+                git clone https://github.com/pershoot/KernelSU-Next/tree/next-susfs PERSHOOT
+                rm -rf kernel/
+                cp -a PERSHOOT/kernel .
+                rm -rf PERSHOOT
+              fi
               [ -f ksun_susfs_latest.patch ] && patch -p1 --forward < ksun_susfs_latest.patch
               #git clone -b next-susfs-dev https://github.com/KernelSU-Next/KernelSU-Next
               #rm  -rf kernel
