Update MY-gki-kernel.yml

diff --git a/.github/workflows/MY-gki-kernel.yml b/.github/workflows/MY-gki-kernel.yml
--- a/.github/workflows/MY-gki-kernel.yml
+++ b/.github/workflows/MY-gki-kernel.yml
@@ -59,7 +59,7 @@ jobs:
       clang_toolchain: ${{ inputs.clang_toolchain }}
       #permissive cause bootloop
       selinux_permissive: false
-      GH_TOKEN: ${{ github.token }}
+      #GH_TOKEN: ${{ secrets.PAT_NO_EXPIRE }}
 
     steps:
       - name: Maximize build space
@@ -79,7 +79,7 @@ jobs:
         with:
           name: linuxxpu
           path: .
-          github-token: '${{ env.GH_TOKEN }}'
+          #github-token: '${{ env.GH_TOKEN }}'
 
       - name: Set CONFIG Environment Variable
         run: |
@@ -114,30 +114,40 @@ jobs:
               latest_update_time=$llvm_latest_relase_date
             fi
             echo "Latest release of $( [ "$clang22_compiler" == "true" ] && echo "clang-22" || echo "llvm"): ${latest_update_time}"
-            clang_llvm_cache_creation_time=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
-            if [ -n "${clang_llvm_cache_creation_time}" ];then
-              echo "clang-llvm-${{ runner.os }}-v1 creation date: ${clang_llvm_cache_creation_time}"
-              if [[ $latest_update_time > $clang_llvm_cache_creation_time ]];then
-                echo "removing old clang-llvm-${{ runner.os }}-v1 from cache ..."
+            clang_custom_cache_creation_time=$(gh cache list --repo $repo -k clang-custom-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+            if [ -n "${clang_custom_cache_creation_time}" ];then
+              echo "clang-custom-${{ runner.os }}-v1 creation date: ${clang_custom_cache_creation_time}"
+              if [[ $latest_update_time > $clang_custom_cache_creation_time ]];then
+                echo "removing old clang-custom-${{ runner.os }}-v1 from cache ..."
                 gh cache delete clang-custom-${{ runner.os }}-v1 --repo $repo
               fi
             else
               echo "clang-custom-${{ runner.os }}-v1 cache not found in ${repo}"
             fi
           else
-            clang_llvm_cache_creation_time=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
-            # remove clang-official-${{ runner.os }}-v1 cache if newer version detected
             current_clang_official_ver_cached=${{ vars.CLANG_OFFICIAL }}
             wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/mirror-goog-main-llvm-toolchain-source/README.md
             url="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/$(grep -Eo 'Android Linux Kernel.+for Android Mainline kernel.' README.md | grep -Eo 'clang-[^ ]+').tar.gz"
+            clang_official_cache_creation_time=$(gh cache list --repo $repo -k clang-official-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+            online_clang_official_ver=$(echo $url | rev | cut -d'/' -f1 | rev)
+            # remove clang-official-${{ runner.os }}-v1 cache if newer version detected
             if curl --output /dev/null --silent --head --fail "$url" 2>/dev/null; then
-              online_clang_official_ver=$(echo $url | rev | cut -d'/' -f1 | rev)
-              if [ "${current_clang_official_ver_cached}" != "${online_clang_official_ver}" ];then
+              if [ -n "${clang_official_cache_creation_time}" ];then
+                if [ "${current_clang_official_ver_cached}" != "${online_clang_official_ver}" ];then
+                  echo "setting global CLANG_OFFICIAL var to: \"${online_clang_official_ver}\""
+                  gh  -R $repo variable set CLANG_OFFICIAL --body "${online_clang_official_ver}"
+                  echo "removing outdated clang-official-${{ runner.os }}-v1 from cache ..."
+                  gh cache delete clang-official-${{ runner.os }}-v1 --repo $repo 2>/dev/null
+                fi
+              else
+                echo "clang-official-${{ runner.os }}-v1 not found in cache list"
+                echo "setting global CLANG_OFFICIAL var to: \"${online_clang_official_ver}\""
+                gh  -R $repo variable set CLANG_OFFICIAL --body "${online_clang_official_ver}"
               fi
-            fi
-            if [ $(echo $(( ($(date +%s) - $(date --date=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' | grep 'createdAt' | cut -d'"' -f4) +%s) )/(60*60*24) ))) -gt 29 ];then
-              echo "removing clang-llvm-${{ runner.os }}-v1 from cache ..."
-              gh cache delete clang-llvm-${{ runner.os }}-v1 --repo $repo 2>/dev/null
+            else
+              echo "Error: aosp clang toolchain download link was not extracted correctly !!! "
+              exit 56
+              false
             fi
           fi
           
@@ -164,52 +174,48 @@ jobs:
           git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
           git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1 mkbootimg
       
-      - name: Cache clang-llvm
-        id: cache-clang-llvm
+      - name: Cache clang-custom
+        if: ${{ env.clang_toolchain == 'custom_clang/llvm' }}
+        id: cache-clang-custom
         uses: actions/cache@v4.2.4
         with:
           path: |
-            clang-llvm
-          key: clang-llvm-${{ runner.os }}-v1
+            clang-custom
+          key: clang-custom-${{ runner.os }}-v1
 
-      - name: Download clang-llvm (if cache not found)
-        if: steps.cache-clang-llvm.outputs.cache-hit != 'true'
+      - name: Download clang-custom (if cache not found)
+        if: steps.cache-clang-custom.outputs.cache-hit != 'true'
         run: |
-          mkdir -p clang-llvm
-          if false;then
-            clang_llvm_latest_url=$(curl -s https://api.github.com/repos/$( [ "${{ env.clang22_compiler }}" == "true" ] && echo "ZyCromerZ/Clang" || echo "llvm/llvm-project")/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep -E '/(Clang-22.+.tar.gz|[^/]+Linux-X64.tar.xz)$')
-            [ -z $clang_llvm_latest_url ] && { echo 'The clang-llvm download link could not be extracted!!!';false; } || echo -e "Download link for the latest build of clang-llvm:\n${clang_llvm_latest_url}"
-            aria2c -x 16 -s 16 -o clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") ${clang_llvm_latest_url}
-            tar -x$([ "${{ env.clang22_compiler }}" == "true" ] && echo "z" || echo "J")f clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") -C clang-llvm
-            rm -rf clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz")
-            if [ "$(find clang-llvm -maxdepth 1 -printf %y)" = "dd" ]; then
-              cd clang-llvm
-              dir=$(find . -maxdepth 1 -type d | grep -Ev '\.$')
-              shopt -s dotglob nullglob
-              mv ${dir}/* .
-              rmdir ${dir}
-            fi
-          else
-            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/mirror-goog-main-llvm-toolchain-source/README.md
-            url="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/$(grep -Eo 'Android Linux Kernel.+for Android Mainline kernel.' README.md | grep -Eo 'clang-[^ ]+').tar.gz"
-            if curl --output /dev/null --silent --head --fail "$url" 2>/dev/null; then
-              echo "downloading $(echo $url | rev | cut -d'/' -f1 | rev) toolchain ..."
-              aria2c -x 16 -s 16 -o clang-llvm.tar.gz $url
-              tar -xzf clang-llvm.tar.gz -C clang-llvm
-              rm -rf clang-llvm.tar.gz
-              if [ "$(find clang-llvm -maxdepth 1 -printf %y)" = "dd" ]; then
-                cd clang-llvm
-                dir=$(find . -maxdepth 1 -type d | grep -Ev '\.$')
-                shopt -s dotglob nullglob
-                mv ${dir}/* .
-                rmdir ${dir}
-              fi
-            else
-              echo "Error: aosp clang toolchain download link was not extracted correctly !!! "
-              exit 56
-              false
-            fi
+          mkdir -p clang-custom
+          clang_custom_latest_url=$(curl -s https://api.github.com/repos/$( [ "${{ env.clang22_compiler }}" == "true" ] && echo "ZyCromerZ/Clang" || echo "llvm/llvm-project")/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep -E '/(Clang-22.+.tar.gz|[^/]+Linux-X64.tar.xz)$')
+          [ -z $clang_custom_latest_url ] && { echo 'The clang-llvm download link could not be extracted!!!';false; } || echo -e "Download link for the latest build of clang-llvm:\n${clang_custom_latest_url}"
+          aria2c -x 16 -s 16 -o clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") ${clang_custom_latest_url}
+          tar -x$([ "${{ env.clang22_compiler }}" == "true" ] && echo "z" || echo "J")f clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") -C clang-custom
+          rm -rf clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz")
+          if [ "$(find clang-custom -maxdepth 1 -printf %y)" = "dd" ]; then
+            cd clang-custom
+            dir=$(find . -maxdepth 1 -type d | grep -Ev '\.$')
+            shopt -s dotglob nullglob
+            mv ${dir}/* .
+            rmdir ${dir}
+            cd ..
+            ln -s clang-custom clang-llvm
           fi
+
+      - name: Cache clang-official
+        if: ${{ env.clang_toolchain == 'official' }}
+        id: cache-clang-official
+        uses: actions/cache@v4.2.4
+        with:
+          path: |
+            clang-official
+          key: clang-official-${{ runner.os }}-v1
+
+      - name: Download clang-official (if cache not found)
+        if: steps.cache-clang-official.outputs.cache-hit != 'true'
+        run: |
+          else
+          
           
           
       - name: Set environment variables
