Update MY-gki-kernel.yml

diff --git a/.github/workflows/MY-gki-kernel.yml b/.github/workflows/MY-gki-kernel.yml
--- a/.github/workflows/MY-gki-kernel.yml
+++ b/.github/workflows/MY-gki-kernel.yml
@@ -86,39 +86,47 @@ jobs:
             
       - name: delete toolchain and clang-llvm caches if older than a certain amount
         run: |
-          repo="${{ github.repository_owner }}/${{ github.event.repository.name }}"
-          clang22_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
-          llvm_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/llvm/llvm-project/releases  | grep -Eo '"name":[^,]+' | grep 'Linux-X64.tar.xz"' | head -n 1)
-          [ -z "$clang22_latest_relase" ] && { echo "Failed to extract clang22 latest release";exit 1;false; }
-          [ -z "$llvm_latest_relase" ] && { echo "Failed to extract llvm latest release";exit 1;false; }
-          clang22_latest_release_date=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases |tr ',' '\n' | grep -E '("name":.*Clang.+.tar.gz"|"created_at":.+)' | sed -E -n '/"name":.+/{n;p}' | head -n 1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
-          llvm_latest_relase_date=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/llvm/llvm-project/releases |tr ',' '\n' | grep -E '("name":.+Linux-X64.tar.xz"|"created_at":.+)' | sed -E -n '/"name":.+/{n;p}' | head -n 1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
-          [ -z "$clang22_latest_release_date" ] && { echo "Failed to extract clang22 latest release date";exit 1;false; }
-          [ -z "$llvm_latest_relase_date" ] && { echo "Failed to extract llvm latest release date";exit 1;false; }
-          if [[ $clang22_latest_release_date > $llvm_latest_relase_date ]];then
-            clang22_compiler=true
-            echo "clang22_compiler=true" >> $GITHUB_ENV
-            latest_update_time=$clang22_latest_release_date
-          else
-            llvm_compiler=true
-            echo "llvm_compiler=true" >> $GITHUB_ENV
-            latest_update_time=$llvm_latest_relase_date
-          fi
-          echo "Latest release of $( [ "$clang22_compiler" == "true" ] && echo "clang-22" || echo "llvm"): ${latest_update_time}"
-          clang_llvm_cache_creation_time=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
-          if [ -n "${clang_llvm_cache_creation_time}" ];then
-            echo "clang-llvm-${{ runner.os }}-v1 creation date: ${clang_llvm_cache_creation_time}"
-            if [[ $latest_update_time > $clang_llvm_cache_creation_time ]];then
-              echo "removing old clang-llvm-${{ runner.os }}-v1 from cache ..."
-              gh cache delete clang-llvm-${{ runner.os }}-v1 --repo $repo
+          if false;then
+            repo="${{ github.repository_owner }}/${{ github.event.repository.name }}"
+            clang22_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
+            llvm_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/llvm/llvm-project/releases  | grep -Eo '"name":[^,]+' | grep 'Linux-X64.tar.xz"' | head -n 1)
+            [ -z "$clang22_latest_relase" ] && { echo "Failed to extract clang22 latest release";exit 1;false; }
+            [ -z "$llvm_latest_relase" ] && { echo "Failed to extract llvm latest release";exit 1;false; }
+            clang22_latest_release_date=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases |tr ',' '\n' | grep -E '("name":.*Clang.+.tar.gz"|"created_at":.+)' | sed -E -n '/"name":.+/{n;p}' | head -n 1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
+            llvm_latest_relase_date=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/llvm/llvm-project/releases |tr ',' '\n' | grep -E '("name":.+Linux-X64.tar.xz"|"created_at":.+)' | sed -E -n '/"name":.+/{n;p}' | head -n 1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
+            [ -z "$clang22_latest_release_date" ] && { echo "Failed to extract clang22 latest release date";exit 1;false; }
+            [ -z "$llvm_latest_relase_date" ] && { echo "Failed to extract llvm latest release date";exit 1;false; }
+            if [[ $clang22_latest_release_date > $llvm_latest_relase_date ]];then
+              clang22_compiler=true
+              echo "clang22_compiler=true" >> $GITHUB_ENV
+              latest_update_time=$clang22_latest_release_date
+            else
+              llvm_compiler=true
+              echo "llvm_compiler=true" >> $GITHUB_ENV
+              latest_update_time=$llvm_latest_relase_date
+            fi
+            echo "Latest release of $( [ "$clang22_compiler" == "true" ] && echo "clang-22" || echo "llvm"): ${latest_update_time}"
+            clang_llvm_cache_creation_time=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+            if [ -n "${clang_llvm_cache_creation_time}" ];then
+              echo "clang-llvm-${{ runner.os }}-v1 creation date: ${clang_llvm_cache_creation_time}"
+              if [[ $latest_update_time > $clang_llvm_cache_creation_time ]];then
+                echo "removing old clang-llvm-${{ runner.os }}-v1 from cache ..."
+                gh cache delete clang-llvm-${{ runner.os }}-v1 --repo $repo
+              fi
+            else
+              echo "clang-llvm-${{ runner.os }}-v1 cache not found in ${repo}"
             fi
           else
-            echo "clang-llvm-${{ runner.os }}-v1 cache not found in ${repo}"
+            # clang-llvm older than 30 days
+            if [ $(echo $(( ($(date +%s) - $(date --date=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' | grep 'createdAt' | cut -d'"' -f4) +%s) )/(60*60*24) ))) -gt 29 ];then
+              echo "removing clang-llvm-${{ runner.os }}-v1 from cache ..."
+              gh cache delete clang-llvm-${{ runner.os }}-v1 --repo $repo
+            fi
           fi
           
-          #toolchain older than 30 days
+          # toolchain older than 30 days
           if [ $(echo $(( ($(date +%s) - $(date --date=$(gh cache list --repo $repo -k toolchain-${{ runner.os }}-v1 --json  'createdAt' | grep 'createdAt' | cut -d'"' -f4) +%s) )/(60*60*24) ))) -gt 29 ];then
-            echo "removing toolchain-${{ runner.os }}-v1 from chache ..."
+            echo "removing toolchain-${{ runner.os }}-v1 from cache ..."
             gh cache delete toolchain-${{ runner.os }}-v1 --repo $repo
           fi
         
@@ -135,7 +143,7 @@ jobs:
         if: steps.cache-toolchain.outputs.cache-hit != 'true'
         run: |
           AOSP_MIRROR=https://android.googlesource.com
-          BRANCH=main-kernel-2026
+          BRANCH=main-kernel-2025
           git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
           git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1 mkbootimg
       
@@ -150,18 +158,22 @@ jobs:
       - name: Download clang-llvm (if cache not found)
         if: steps.cache-clang-llvm.outputs.cache-hit != 'true'
         run: |
-          clang_llvm_latest_url=$(curl -s https://api.github.com/repos/$( [ "${{ env.clang22_compiler }}" == "true" ] && echo "ZyCromerZ/Clang" || echo "llvm/llvm-project")/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep -E '/(Clang-22.+.tar.gz|[^/]+Linux-X64.tar.xz)$')
-          [ -z $clang_llvm_latest_url ] && { echo 'The clang-llvm download link could not be extracted!!!';false; } || echo -e "Download link for the latest build of clang-llvm:\n${clang_llvm_latest_url}"
-          mkdir -p clang-llvm
-          aria2c -x 16 -s 16 -o clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") ${clang_llvm_latest_url}
-          tar -x$([ "${{ env.clang22_compiler }}" == "true" ] && echo "z" || echo "J")f clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") -C clang-llvm
-          rm -rf clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz")
-          if [ "$(find clang-llvm -maxdepth 1 -printf %y)" = "dd" ]; then
-            cd clang-llvm
-            dir=$(find . -maxdepth 1 -type d | grep -Ev '\.$')
-            shopt -s dotglob nullglob
-            mv ${dir}/* .
-            rmdir ${dir}
+          if false;then
+            clang_llvm_latest_url=$(curl -s https://api.github.com/repos/$( [ "${{ env.clang22_compiler }}" == "true" ] && echo "ZyCromerZ/Clang" || echo "llvm/llvm-project")/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep -E '/(Clang-22.+.tar.gz|[^/]+Linux-X64.tar.xz)$')
+            [ -z $clang_llvm_latest_url ] && { echo 'The clang-llvm download link could not be extracted!!!';false; } || echo -e "Download link for the latest build of clang-llvm:\n${clang_llvm_latest_url}"
+            mkdir -p clang-llvm
+            aria2c -x 16 -s 16 -o clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") ${clang_llvm_latest_url}
+            tar -x$([ "${{ env.clang22_compiler }}" == "true" ] && echo "z" || echo "J")f clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz") -C clang-llvm
+            rm -rf clang-llvm.tar.$([ "${{ env.clang22_compiler }}" == "true" ] && echo "gz" || echo "xz")
+            if [ "$(find clang-llvm -maxdepth 1 -printf %y)" = "dd" ]; then
+              cd clang-llvm
+              dir=$(find . -maxdepth 1 -type d | grep -Ev '\.$')
+              shopt -s dotglob nullglob
+              mv ${dir}/* .
+              rmdir ${dir}
+            fi
+          else
+            git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r547379 clang-llvm
           fi
           
           
