updates done by local repo

diff --git a/.github/workflows/MY-gki-kernel.yml b/.github/workflows/MY-gki-kernel.yml
--- a/.github/workflows/MY-gki-kernel.yml
+++ b/.github/workflows/MY-gki-kernel.yml
@@ -84,22 +84,22 @@ jobs:
           echo "CONFIG=$CONFIG" >> $GITHUB_ENV
           echo "CONFIG set to: $CONFIG"  
             
-      - name: delete toolchain and clang-22 caches if older than a certain amount
+      - name: delete toolchain and clang-llvm caches if older than a certain amount
         run: |
           repo="${{ github.repository_owner }}/${{ github.event.repository.name }}"
-          clang_cache_creation_time=$(gh cache list --repo $repo -k clang-22-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+          clang_cache_creation_time=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
           if [ ! -z "${clang_cache_creation_time}" ];then
             clang_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
             [ -z "$clang_latest_relase" ] && { echo "Failed to extract clang latest release";exit 1;false; }
             clang_latest_release_date=$(echo "${clang_latest_relase}" | grep -Eo '[[:digit:]]{8}' | sed -E 's/(.{4})(.{2})(.{2})/\1-\2-\3/g')
-            echo "Latest release of clang-22: $(echo ${clang_latest_relase} | cut -d':' -f2-)"
-            echo "clang-22-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
+            echo "Latest release of clang-llvm: $(echo ${clang_latest_relase} | cut -d':' -f2-)"
+            echo "clang-llvm-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
             if [[ $clang_latest_release_date > $clang_cache_creation_time ]];then
-              echo "removing old clang-22-${{ runner.os }}-v1 from cache ..."
-              gh cache delete clang-22-${{ runner.os }}-v1 --repo $repo
+              echo "removing old clang-llvm-${{ runner.os }}-v1 from cache ..."
+              gh cache delete clang-llvm-${{ runner.os }}-v1 --repo $repo
             fi
           else
-            echo "clang-22-${{ runner.os }}-v1 cache not found in ${repo}"
+            echo "clang-llvm-${{ runner.os }}-v1 cache not found in ${repo}"
           fi
           
           #toolchain older than 30 days
@@ -125,23 +125,23 @@ jobs:
           git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
           git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1 mkbootimg
       
-      - name: Cache clang-22
-        id: cache-clang-22
+      - name: Cache clang-llvm
+        id: cache-clang-llvm
         uses: actions/cache@v4.2.4
         with:
           path: |
-            clang-22
-          key: clang-22-${{ runner.os }}-v1
+            clang-llvm
+          key: clang-llvm-${{ runner.os }}-v1
 
-      - name: Download clang-22 (if cache not found)
-        if: steps.cache-clang-22.outputs.cache-hit != 'true'
+      - name: Download clang-llvm (if cache not found)
+        if: steps.cache-clang-llvm.outputs.cache-hit != 'true'
         run: |
           clang_latest_ulr=$(curl -s https://api.github.com/repos/ZyCromerZ/Clang/releases/latest | grep browser_download_url | cut -d '"' -f 4)
-          [ -z $clang_latest_ulr ] && { echo 'The clang-22 download link could not be extracted!!!';false; } || echo -e "Download link for the latest build of clang-22:\n${clang_latest_ulr}"
-          mkdir -p clang-22
-          aria2c -x 16 -s 16 -o clang-22.tar.gz ${clang_latest_ulr}
-          tar -xzf clang-22.tar.gz -C clang-22
-          rm -rf clang-22.tar.gz
+          [ -z $clang_latest_ulr ] && { echo 'The clang-llvm download link could not be extracted!!!';false; } || echo -e "Download link for the latest build of clang-llvm:\n${clang_latest_ulr}"
+          mkdir -p clang-llvm
+          aria2c -x 16 -s 16 -o clang-llvm.tar.gz ${clang_latest_ulr}
+          tar -xzf clang-llvm.tar.gz -C clang-llvm
+          rm -rf clang-llvm.tar.gz
           
       - name: Set environment variables
         run: |
@@ -245,14 +245,14 @@ jobs:
           popd
           sed -E -i 's|(^[[:space:]]+)(\$\(call if_changed,gzip\))|\1\$(srctree)/kernel/manipulating_conf_data.sh $(realpath kernel/config_data)\; \\\n\1\2|g' $CONFIG/common/kernel/Makefile
 
-          # for clang-22
-          if [ -d $GITHUB_WORKSPACE/clang-22 ];then
+          # for clang-llvm
+          if [ -d $GITHUB_WORKSPACE/clang-llvm ];then
             cd $GITHUB_WORKSPACE/$CONFIG
-            #Remove old clang revisions and create a link to clang-22
-            [ -e $GITHUB_WORKSPACE/clang-22/bin/clang ] && clang_bin="$GITHUB_WORKSPACE/clang-22/bin/clang"
+            #Remove old clang revisions and create a link to clang-llvm
+            [ -e $GITHUB_WORKSPACE/clang-llvm/bin/clang ] && clang_bin="$GITHUB_WORKSPACE/clang-llvm/bin/clang"
             [ -z $clang_bin ] && echo "clang not found" && false
             rm -rf prebuilts/clang/host/linux-x86/clang-*
-            cd prebuilts/clang/host/linux-x86/ && ln -s -T $GITHUB_WORKSPACE/clang-22 clang-$($clang_bin -dumpversion)
+            cd prebuilts/clang/host/linux-x86/ && ln -s -T $GITHUB_WORKSPACE/clang-llvm clang-$($clang_bin -dumpversion)
 
             # Update build config constants
             sed -i \
@@ -578,7 +578,7 @@ jobs:
           set -ex
           cd "$CONFIG"
 
-          if [ ! -d $GITHUB_WORKSPACE/clang-22 ];then
+          if [ ! -d $GITHUB_WORKSPACE/clang-llvm ];then
             export LIBRARY_PATH=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/lib64
             export CPATH=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/include
           fi
@@ -719,7 +719,7 @@ jobs:
             false
           fi
 
-          if [ ! -d ${GITHUB_WORKSPACE}/clang-22 ];then
+          if [ ! -d ${GITHUB_WORKSPACE}/clang-llvm ];then
             #for ndk
             export TOOLCHAIN=${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64
             export My_PATH="${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:${ANDROID_NDK_LATEST_HOME}/prebuilt/linux-x86_64/bin/:${PATH}:$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin"
@@ -760,10 +760,10 @@ jobs:
             sed -i 's/-dirty//' ./common/scripts/setlocalversion
             export BUILD_SCRIPT_DIR=$(dirname $(realpath build/build.sh))
 
-            #for ndk and arm-toolchain and clang-22
+            #for ndk and arm-toolchain and clang-llvm
             sed -E -i '/.*sysroot_flags\+=.+/d' build/_setup_env.sh
 
-            if [ ! -d ${GITHUB_WORKSPACE}/clang-22 ];then
+            if [ ! -d ${GITHUB_WORKSPACE}/clang-llvm ];then
               sed -E -i 's|source .+_setup_env.sh.+|source "${ROOT_DIR}/build/_setup_env.sh";export PATH="${My_PATH}"|g' build/build.sh
               sed -E -i 's|.*export ROOT_DIR=.+dirname.+$|export ROOT_DIR=$($(find ${BUILD_SCRIPT_DIR} -type f -name "gettop.sh"))|g' build/build.sh
               sed -E -i 's|(if \[ -n \"\$\{MODULES_ORDER\}\" \]\;.+)|\1\n  cp ${OUT_DIR}/modules.order ${KERNEL_DIR}/${MODULES_ORDER}\n|g' build/build.sh
diff --git a/.github/workflows/cli.yml b/.github/workflows/cli.yml
--- a/.github/workflows/cli.yml
+++ b/.github/workflows/cli.yml
@@ -91,15 +91,15 @@ jobs:
             latest_update_time=$llvm_latest_relase_date
           fi
           echo "Latest release of $( [ "$clang22_compiler" == "true" ] && echo "clang-22" || echo "llvm"): ${latest_update_time}"
-          clang_cache_creation_time=$(gh cache list --repo $repo -k clang-${{ runner.os }}-v2 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
-          if [ -n "${clang_cache_creation_time}" ];then
-            echo "clang-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
-            if [[ $latest_update_time > $clang_cache_creation_time ]];then
-              echo "removing old clang-${{ runner.os }}-v1 from cache ..."
-              gh cache delete clang-${{ runner.os }}-v1 --repo $repo
+          clang-llvm_cache_creation_time=$(gh cache list --repo $repo -k clang-llvm-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+          if [ -n "${clang-llvm_cache_creation_time}" ];then
+            echo "clang-llvm-${{ runner.os }}-v1 creation date: ${clang-llvm_cache_creation_time}"
+            if [[ $latest_update_time > $clang-llvm_cache_creation_time ]];then
+              echo "removing old clang-llvm-${{ runner.os }}-v1 from cache ..."
+              gh cache delete clang-llvm-${{ runner.os }}-v1 --repo $repo
             fi
           else
-            echo "clang-${{ runner.os }}-v1 cache not found in ${repo}"
+            echo "clang-llvm-${{ runner.os }}-v1 cache not found in ${repo}"
           fi
           
 
