Update MY-gki-kernel.yml

diff --git a/.github/workflows/MY-gki-kernel.yml b/.github/workflows/MY-gki-kernel.yml
--- a/.github/workflows/MY-gki-kernel.yml
+++ b/.github/workflows/MY-gki-kernel.yml
@@ -79,15 +79,26 @@ jobs:
       - name: delete toolchain and clang-22 caches if older than a certain amount
         run: |
           repo="${{ github.repository_owner }}/${{ github.event.repository.name }}"
-        
-          #clang older than 30 days
-          if [ $(echo $(( ($(date +%s) - $(date --date=$(gh cache list --repo $repo -k clang-22-${{ runner.os }}-v1 --json  'createdAt' | grep 'createdAt' | cut -d'"' -f4) +%s) )/(60*60*24) ))) -gt 29 ];then
-            echo "remove clang-22-${{ runner.os }}-v1 from chache ..."
-            gh cache delete clang-22-${{ runner.os }}-v1 --repo $repo
+          clang_cache_creation_time=$(gh cache list --repo $repo -k clang-22-${{ runner.os }}-v1 --json  'createdAt' 2>/dev/null  | grep 'createdAt' | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}') || true
+          if [ ! -z "${clang_cache_creation_time}" ];then
+            clang_latest_relase=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ZyCromerZ/Clang/releases  | grep -Eo '"name":[^,]+' | head -n 1)
+            [ -z "$clang_latest_relase" ] && { echo "Failed to extract clang latest release";exit 1;false; }
+            clang_latest_release_date=$(echo "${clang_latest_relase}" | grep -Eo '[[:digit:]]{8}' | sed -E 's/(.{4})(.{2})(.{2})/\1-\2-\3/g')
+            if [[ $clang_latest_release_date > $clang_cache_creation_time ]];then
+              echo "Latest release of clang-22: $(echo ${clang_latest_relase} | cut -d':' -f2-)"
+              echo "clang-22-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
+              echo "removing old clang-22-${{ runner.os }}-v1 from cache ..."
+              gh cache delete clang-22-${{ runner.os }}-v1 --repo $repo
+            fi
+            echo "Latest release of clang-22: $(echo ${clang_latest_relase} | cut -d':' -f2-)"
+            echo "clang-22-${{ runner.os }}-v1 creation date: ${clang_cache_creation_time}"
+          else
+            echo "clang-22-${{ runner.os }}-v1 cache not found in ${repo}"
           fi
+          
           #toolchain older than 30 days
           if [ $(echo $(( ($(date +%s) - $(date --date=$(gh cache list --repo $repo -k toolchain-${{ runner.os }}-v1 --json  'createdAt' | grep 'createdAt' | cut -d'"' -f4) +%s) )/(60*60*24) ))) -gt 29 ];then
-            echo "remove toolchain-${{ runner.os }}-v1 from chache ..."
+            echo "removing toolchain-${{ runner.os }}-v1 from chache ..."
             gh cache delete toolchain-${{ runner.os }}-v1 --repo $repo
           fi
         
